[build.environment]
  NODE_VERSION = "20"

[build]
  base = "website"
  publish = "dist"

[context.production]
  command = "VITE_HOSTNAME=$URL pnpm test"

[context.deploy-preview]
  command = "VITE_HOSTNAME=$DEPLOY_PRIME_URL pnpm test"
